### ISSUE TITLE
method 'create_bid' failed: RequestFailed: {"status": "error", "errors": [{"location": "body", "name": "parameters", "description": ["This field is required."]}]}

### ISSUE THREAD

**Issue by AvchinnikovaOksana** [openprocurement/robot_tests#172]
meatTender - role:provider - тест "Можливість подати цінову пропозицію з неціновим показником другим учасником"

отправляются данные:
```
data:
    tenderers:
    -   address:
            countryName: Україна
            countryName_en: Ukraine
            countryName_ru: Украина
            locality: м. Вінниця
            postalCode: '21100'
            region: Вінницька область
            streetAddress: 6461 Бгиденко Knolls Apt. 990
        contactPoint:
            name: Одарка Даньків
            telephone: +38 641 678-93-68
        identifier:
            id: 00002879
            scheme: UA-EDR
        name: Карпа-Пилипенко
    value:
        amount: 1510
        currency: UAH
        valueAddedTaxIncluded: true
parameters:
-   code: ee3e24bc17234a41bd3e3a04cc28e9c6
    value: 0.05
-   code: 48cfd91612c04125ab406374d7cc8d93
    value: 0.01
```

ошибка: 
`Calling method 'create_bid' failed: RequestFailed: {"status": "error", "errors": [{"location": "body", "name": "parameters", "description": ["This field is required."]}]}`

**Comment by Leits** [comment]
parameters мали б бути на рівень вище:
```
data:
    tenderers: ...
    value: ...
    parameters: ...
```
Чи не могли б ви надіслати log?
